version: '2'
services:
  web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./:/var/www/html
        - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
  php:
    build:
      context: .
      dockerfile: ./docker-config/php/Dockerfile
    expose:
      - 9000
    volumes:
      - ./:/var/www/html/